name = "LatticeParticlesMC"
uuid = "92709574-4550-412a-a828-286bee8f3ea2"
authors = ["Romain Simon", "Leonardo Galliano"]
version = "0.1.0"

[deps]
Arianna = "07692032-97b4-4f8d-80d7-e18df88d31a9"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
Arianna = "0.1.4"
Printf = "1.11.0"
StaticArrays = "1.9.13"
Statistics = "1.11.1"
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
